import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Login with Google': 'Login with Google',
          'Sign up with Google': 'Sign up with Google',
          "Don't have an account? ": "Don't have an account? ",
          'Register Now': 'Register Now',
          'drive with us.': 'Drive with us.',
          'earn extra money': 'Earn extra money',
          'Infos': 'Infos',
          "Infos taxi " : "Infos taxi ",
          'Driver': 'Driver',
          'Already have an account?': 'Already have an account?',
          'Login Now': 'Login Now',
          'Events': 'Events',
          'Let others know': 'Let others know',
          'Share customer\'s details': 'Share customer\'s details',
          'Waiting Customers': 'Waiting Customers',
          'SEND': 'SEND',
          'Success': 'Success',
          'Your information has been sent': 'Your information has been sent',
          'Event': 'Event',
          'Date': 'Date',
          'Time:': 'Time:',
          'Expected Passengers': 'Expected Passengers',
          'Location': 'Location',
          'My Location': 'My Location',
          'User unknown': 'User unknown',
          'unable to load image': 'unable to load image',
          'Share Info': 'Share Info',
          'Get Fare': 'Get Fare',
          'Contact': 'Contact',
          'Profile': 'Profile',
          'Get Your Fare': 'Get Your Fare',
          'Enter your message': 'Enter your message',
          'Send': 'Send',
          'Contact Us': 'Contact Us',
          'Quick Links': 'Quick Links',
          'Logout': 'Logout',
          "Driver's Location" : "Driver's Location",
          'Driver Details' : 'Driver Details',
          'More Details:' : 'More Details:',
          'Name: ' : 'Name: ',
          'Location Address: ' : 'Location Address: ',
          'Waiting Passengers: ' : 'Waiting Passengers: ',
          'Share Information' : 'Share Information',
          'Edit Profile' : 'Edit Profile',
          'Classified ADS' : "Classified ADS",
          'Rides' : 'Rides',
          'Ride uploaded' : 'Ride uploaded',
          'Thanks for listing your ride' : "Thanks for listing your ride", 
          'Ad uploaded' : 'Ad uploaded',
          'Thanks for listing your ad' : 'Thanks for listing your ad',
          'No fares yet' : 'No fares yet',
          'Items': 'Items',
          'Number of lines' : 'Number of lines',
          'Departure city' : 'Departure city',
          'Arrival city' : 'Arrival city',
          'Add your listing' : 'Add your listing ',
          'No lines found' : 'No lines found',
          'No ads found' : 'No ads found',
          'Get fare' : 'Get fare',
          'No of lines' : 'No of lines',
          'Username' : 'Username',
          'Phone number' : 'Phone number',
          'No Rides found' : 'No Rides found',
          'No Fares yet' : 'No Fares yet',
          

        },
        'fr_FR': {
          'Login with Google': 'Se connecter avec Google',
          'Sign up with Google': "S'inscrire avec Google",
          "Don't have an account? ": "Vous n'avez pas de compte? ",
          'Register Now': "S'inscrire maintenant",
          'drive with us.': 'Conduisez avec nous.',
          'earn extra money': "gagner de l'argent supplémentaire",
          'Infos': 'Infos',
          'Driver': 'Chauffeur',
          'Already have an account?': 'Vous avez de l\'account?',
          'Login Now': 'Se connecter maintenant',
          'Events': ' Événement de la semaine',
          'Let others know': 'partagez l\'information',
          'Share customer\'s details': 'clients en attente dans votre zone',
          'Waiting Customers': 'Clients en attente',
          'SEND': 'ENVOYER',
          'Success': 'Succès',
          'Your information has been sent': 'Vos informations ont été envoyées',
          'Event': 'Événement',
          'Date': 'Date',
          'Time:': 'Heure:',
          'Expected Passengers': 'Passagers attendus',
          'Location': 'Emplacement',
          'My Location': 'Mon emplacement',
          'User unknown': 'Utilisateur inconnu',
          'unable to load image': 'impossible de charger l\'image',
          'Share Info': ' informations',
          'Get Fare': 'charge',
          'Contact': 'Contact',
          'Profile': 'Profil',
          'Get Your Fare': 'zone de charge',
          'Enter your message': 'Entrez votre message',
          'Send': 'Envoyer',
          'Contact Us': 'Nous contacter',
          'Quick Links': 'Liens Rapides',
          'Logout': 'Se déconnecter',
          "Driver's Location" : "Emplacement du conducteur",
          'Driver Details' : 'Details du conducteur',
          'More Details:' : 'Plus de details:',
          'Name: ' : 'Nom: ',
          'Location Address: ' : 'Adresse de l\'emplacement: ',
          'Waiting Passengers: ' : 'nombre de clients en attente: ',
          'Share Information' : 'Partager les info',
          'Edit Profile' : 'Modifier le profil',
          'Classified ADS' : "Annonces",
          'Rides' : 'Courses',
          'Ride uploaded' : 'Trajet téléchargé',
          'Thanks for listing your ride' : "Merci pour la liste de votre trajet", 
          'Ad uploaded' : 'Annonce telechargée',
          'Thanks for listing your ad' : 'Merci pour la liste de votre annonce',
          'No fares yet' : 'pas encore d\'infos',
          'Items': 'Description',
          'Number of lines' : 'ajouter votre annonce',
          'Departure city' : 'Départ',
          'Arrival city' : 'Destination',
          'Add your listing' : 'ajouter votre annonce',
          'No lines found' : 'aucune ligne n\'a été trouvée',
          'No ads found' : 'aucune annonce n\'a été trouvée',
          'Get fare' : 'charge',
          'No of lines' : 'ajouter votre annonce',
          'Username' : 'Nom d\'utilisateur',
          'Phone number' : 'Numéro de téléphone',
          'No Rides found' : 'aucune course n\'a été trouvée',
          'No Fares yet' : 'pas encore de tarifs',


        },
      };
}